-- ==========================================
-- RELATIONAL DATABASE PRACTICE SCHEMA
-- System: Roue and Voiture Tables
-- Description: This script sets up two related tables: 'voiture' and 'roue'.
-- The 'roue' table contains a foreign key referencing the 'voiture' table.
-- It also populates both tables with dummy data for practice purposes.
-- ==========================================

-- 1. Cleanup (Drop tables if they exist to start fresh)
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE roue';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE voiture';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

-- 2. Create voiture Table
CREATE TABLE voiture (
    id_voiture NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    marque VARCHAR2(50),
    modele VARCHAR2(50),
    annee NUMBER,
);

-- 3. Create roue Table (Relational Link)
CREATE TABLE roue (
    order_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_voiture NUMBER,
    TYPE_ROUE VARCHAR2(50),
    DIAMETRE NUMBER, 
    CONSTRAINT con_voiture
        FOREIGN KEY (id_voiture)
        REFERENCES voiture(id_voiture)
);

-- 4. Insert Dummy Data
--voiture 
INSERT INTO voiture (marque, modele, annee) VALUES ('toyota', 'Corolla', 2020);
INSERT INTO voiture (marque, modele, annee) VALUES ('Honda', 'Civic', 2019);
INSERT INTO voiture (marque, modele, annee) VALUES ('Ford', 'Focus', 2018);
insert into voiture (marque, modele, annee) VALUES ('Porsche','918 Spider',2021)
-- roue (Linking to voiture)
INSERT INTO roue (id_voiture, TYPE_ROUE, DIAMETRE) VALUES (1, 'Alloy', 16);
INSERT INTO roue (id_voiture, TYPE_ROUE, DIAMETRE) VALUES (1, 'Steel', 15);
INSERT INTO roue (id_voiture, TYPE_ROUE, DIAMETRE) VALUES (2, 'Chrome', 17);

-- 5. Commit changes
COMMIT;

-- 6. Verify Data
SELECT 'Database Setup Complete!' AS status FROM dual;
