-- ==========================================
-- RELATIONAL DATABASE PRACTICE SCHEMA
-- System: E-Commerce Mini
-- ==========================================

-- 1. Cleanup (Drop tables if they exist to start fresh)
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE orders';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE customers';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

-- 2. Create Customers Table
CREATE TABLE customers (
    customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(50),
    last_name VARCHAR2(50),
    email VARCHAR2(100),
    join_date DATE DEFAULT SYSDATE
);

-- 3. Create Orders Table (Relational Link)
CREATE TABLE orders (
    order_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id NUMBER,
    order_date DATE DEFAULT SYSDATE,
    total_amount NUMBER(10, 2),
    status VARCHAR2(20) DEFAULT 'Pending',
    CONSTRAINT fk_customer
        FOREIGN KEY (customer_id)
        REFERENCES customers(customer_id)
);

-- 4. Insert Dummy Data
-- Customers
INSERT INTO customers (first_name, last_name, email) VALUES ('John', 'Doe', 'john@example.com');
INSERT INTO customers (first_name, last_name, email) VALUES ('Jane', 'Smith', 'jane@test.com');
INSERT INTO customers (first_name, last_name, email) VALUES ('Ali', 'Baba', 'ali@open.com');

-- Orders (Linking to customers)
INSERT INTO orders (customer_id, total_amount, status) VALUES (1, 150.00, 'Shipped');
INSERT INTO orders (customer_id, total_amount, status) VALUES (1, 450.50, 'Pending');
INSERT INTO orders (customer_id, total_amount, status) VALUES (2, 89.99, 'Delivered');

-- 5. Commit changes
COMMIT;

-- 6. Verify Data
SELECT 'Database Setup Complete!' AS status FROM dual;